name: Push to hatenablog

on:
  push:
    branches:
      - release/**

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # blogsyncをセットアップする。
      - name: Setup blogsync
        env:
          BSY: ${{ secrets.BSY }}
        run: |
          if !(type ~/go/bin/blogsync > /dev/null 2>&1); then
            go install github.com/x-motemen/blogsync@v0.13.0;
          fi
          echo -e ${BSY} > blogsync.yaml

      # featureブランチとmainブランチの間に差分があれば、プッシュする。
      - name: Exec blogsync push
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
        run: |          
          git diff origin/main --name-only \
            | grep dist/entry \
            | xargs -t -n1 ~/go/bin/blogsync push
