name: push to hatena blog

on:
  push:
    branches:
      - feature/**

jobs:
  push:
    name: push
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - uses: actions/cache@v1
        with:
          path: ~/go/bin/
          key: ${{ runner.os }}-go-blogsync-200423.0756
          restore-keys: |
            ${{ runner.os }}-go-blogsync-200423.0756
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git fetch
      - run: |
          git fetch origin main

      - name: Setup blogsync
        env:
          BSY: ${{ secrets.BSY }}
        run: |
          if !(type ~/go/bin/blogsync > /dev/null 2>&1); then
            go get github.com/x-motemen/blogsync;
          fi
          echo -e ${BSY} > blogsync.yaml

      - name: push
        env:
          DOMAIN: ${{ secrets.DOMAIN }}
        run: |
          git diff origin/main --name-only \
          | grep dist/entry \
          | xargs -t -n1 ~/go/bin/blogsync push
